
#工作名字
name: tly-checkin
#
on:
  schedule:
  # 定时任务 想要运行的时间-8即为填入值例如：bj11点运行 填11-8=3
    - cron:  34 1 * * * 

jobs:
#将工作流程中运行的所有作业组合在一起
  checkin:
  #定义名为 checkin 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-22.04
    #将作业配置为在最新版本的 Ubuntu Linux 运行器上运行
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - uses: actions/checkout@v2
#uses 关键字指定此步骤将运行 actions/checkout 操作的 v3。 这是一个将存储
#库签出到运行器上的操作，允许您对代码（如生成和测试工具）运行脚本或其他操
#作。 每当工作流程将针对存储库的代码运行时，都应使用签出操作。
    
    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip install requests
      # pip3 install -r requirements.txt
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Checkin
      run: |
        python3 ./tlyauto.py 
      env: #设置secrets的环境变量
        COOKIE1: ${{ secrets.COOKIEW }}
        TOKEN: ${{ secrets.BHSHARE_TOKEN }}
        MAIL2: ${{ secrets.TLY_ACCOUNT_2 }}
        MAIL1: ${{ secrets.TLY_ACCOUNT_W }}
        MAIL3: ${{ secrets.TLY_ACCOUNT_G }}

