
#工作名字
name: tly-checkin
#
on:
  schedule:
  # 定时任务，在每天的8点推送签到信息到邮箱
    - cron:  0 18 * * * 

jobs:
#将工作流程中运行的所有作业组合在一起
  checkin:
  #定义名为 checkin 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest
    #将作业配置为在最新版本的 Ubuntu Linux 运行器上运行
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - uses: actions/checkout@v2
#uses 关键字指定此步骤将运行 actions/checkout 操作的 v3。 这是一个将存储
#库签出到运行器上的操作，允许您对代码（如生成和测试工具）运行脚本或其他操
#作。 每当工作流程将针对存储库的代码运行时，都应使用签出操作。
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.0'
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip install requests
      # pip3 install -r requirements.txt
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Checkin
      run: |
        python3 ./tlyauto.py 
 # env: 
  #设置secrets的环境变量
  #  COOKIE1: ${{ secrets.COOKIE1 }}
   # COOKIE2: ${{ secrets.COOKIE2 }}
    # SMTP: ${{ secrets.SMTP }}
   # MAIL1: ${{ secrets.TLY_ACCOUNT_2 }}
   # MAIL2: ${{ secrets.TLY_ACCOUNT_W }}

