name: w-tly-checkin            #工作名字
on:
  workflow_dispatch:
  schedule:       # 定时任务 想要运行的时间-8即为填入值例如：bj8点运行 填8-8=0
    - cron:  15,45 8,9 * * * 

jobs:             
  checkin:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.18
    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Checkin
      run: |
        python3 ./tlyauto.py 
      env: #设置secrets的环境变量
        COOKIE1: ${{ secrets.COOKIEW }}
        TOKEN: ${{ secrets.BHSHARE_TOKEN }}

